force-app/main/default/objects/Account/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Mileage__c</fullName>
    <label>Monthly Mileage</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <description>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</description>
    <inlineHelpText>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</inlineHelpText>
    <label>Standard Vehicle Make Model and Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Day_Of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_Of_Week__c</fullName>
    <label>Day Of Week</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End date and time of the trips.</description>
    <label>EndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Fuel_price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_price__c</fullName>
    <label>Fuel price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start date and time of the trips.</description>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Stay_Time__c.field-meta.xml
<CustomField>
    <fullName>Stay_Time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stay Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>TimeZone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Status__c</fullName>
    <label>Trip Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Approved Yet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/IRS_Mileage_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Mileage_Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>IRS Mileage Rate</description>
    <label>IRS Mileage Rate</label>
    <referenceTo>IRS_Mileage_Rate__c</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Monthly_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Mileage__c</fullName>
    <label>Monthly Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>VALUE(RIGHT(Month__c,Find(&quot;-&quot;, Month__c)+1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IRS_Mileage_Rate__c/IRS_Mileage_Rate__c.object-meta.xml
<CustomObject>
    <label>IRS Mileage Rate</label>
    <nameField>
        <displayFormat>IRS Rate-{0000}</displayFormat>
        <label>IRS Mileage Rate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Mileage Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IRS_Mileage_Rate__c/fields/IRS_Rate__c.field-meta.xml
<CustomField>
    <fullName>IRS_Rate__c</fullName>
    <description>IRS Rate this month</description>
    <inlineHelpText>IRS Rate this month</inlineHelpText>
    <label>IRS Rate this month</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IRS_Mileage_Rate__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendEmail__c/SendEmail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Send Email</label>
</CustomObject>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailToMe__c/SendEmailToMe__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SendEmailToMe</label>
</CustomObject>

force-app/main/default/objects/SendEmailToMe__c/fields/Send_email_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_email_to_me__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send email to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/TriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TriggerConfig:- MappingGasPriceTrigger</description>
    <label>TriggerConfig</label>
</CustomObject>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriggersendEmailForNewContact__c.field-meta.xml
<CustomField>
    <fullName>ContactTriggersendEmailForNewContact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use in contact trigger helper class for sendEmailForNewContact method.</description>
    <label>ContactTriggersendEmailForNewContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/Vehicle_URL_Mapping__c.object-meta.xml
<CustomObject>
    <label>Vehicle URL Mapping</label>
    <nameField>
        <label>Vehicle URL Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle URL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SendEmailForSubmittedMileageTest.cls
@istest
public class SendEmailForSubmittedMileageTest {
    public static testmethod void testMethod4(){
        

        SendEmail__c customSetting1 =  new SendEmail__c();
        customSetting1.Name = 'SendEmailForSubmittedMileage';
        customSetting1.Send_email_from_code__c= true;
        insert customSetting1;
        
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        insert customEmailSetting;
        
        SendEmail__c customSetting2 =  new SendEmail__c();
        customSetting2.Name = 'Send Email For Compliance';
        customSetting2.Send_email_from_code__c= true;
        insert customSetting2;
        
        SendEmailToMe__c  objSendEmailToMe = new SendEmailToMe__c();
        objSendEmailToMe.Name = 'SendEmailForSubmittedMileage';
        objSendEmailToMe.Send_email_to_me__c = true;
        insert objSendEmailToMe;

        Account acc = TestUtilityClass.getTestSingleAccount();
        
        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093359.jpg';
        veh.vehicle__c =  'Full-Size Sedan';
        veh.Year__c = '2019';
        insert veh;
        //RecordUtilityClass.vehicleUrlMapping();

        Contact con = RecordUtilityClass.buildAdminContact(acc);
        con.Role__c = 'Driver';
        con.Vehicle_Type__c = '2019 Full-Size Sedan';
        con.Time_Zone__c = 'US/Mountain' ;
        insert con;
        //Contact con = TestUtilityClass.getTestSingleContact(acc);
        //Employee_Reimbursement__c emp = TestUtilityClass.getTestEmployeeReimbursement3(con);
        
        IRS_Mileage_Rate__c obj_IRS_Mileage_Rate_3 = new IRS_Mileage_Rate__c();
        obj_IRS_Mileage_Rate_3.year__c='2020';
        obj_IRS_Mileage_Rate_3.IRS_Rate__c =0.567;
        insert obj_IRS_Mileage_Rate_3;
        
        Employee_Reimbursement__c empReim = new Employee_Reimbursement__c();
        RG_InsertLastMonthReimbursement ilmr = new RG_InsertLastMonthReimbursement();
        
        empReim.Contact_Id__c = con.id;
        empReim.Name = 'Test';
        empReim.Fuel_Price__c = 12;
        empReim.MPG__c = 45;
        empReim.Month__c =  ilmr.getLastMonthValue(-1);
        //empReim.Month__c =  '01-2020';
        empReim.Approved_Date__c = null;
        empReim.Monthly_Mileage__c = 50;
        empReim.IRS_Mileage_Rate__c =obj_IRS_Mileage_Rate_3.id;
        empReim.Maintenance_and_Tires__c =10;
        insert empReim;
        
        Employee_Mileage__c emp = new Employee_Mileage__c();
        emp.EmployeeReimbursement__c = empReim.id;
        emp.Contact_Email_Id__c = con.External_Email__c;
        emp.Name = 'Test Mileage Record';
        emp.Trip_Status__c = StaticValues.noApprovedYet;
        emp.TimeZone__c = 'US/Mountain' ;
        emp.Mileage__c = 10.00;
        emp.Day_Of_Week__c = 'Mon';
        emp.Stay_Time__c = 10;
        emp.Fuel_price__c = 10.00;
        emp.StartTime__c = system.now();
        emp.EndTime__c =  system.now();
        insert emp;
            
        
        SendEmailForSubmittedMileage mil = new SendEmailForSubmittedMileage();
         Database.executeBatch(mil, 1);
    }
}