force-app/main/default/objects/Account/fields/Triplog_API__c.field-meta.xml
<CustomField>
    <fullName>Triplog_API__c</fullName>
    <label>Triplog API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>Add-{00000}</displayFormat>
        <label>Address No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <label>Abbreviation</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Anchorage</fullName>
                <label>(GMT-08:00) Alaska Daylight Time (America/Anchorage)</label>
            </value>
            <value>
                <fullName>America/El_Salvador</fullName>
                <label>(GMT-06:00) Central Standard Time (America/El_Salvador)</label>
            </value>
            <value>
                <fullName>America/Chicago</fullName>
                <label>(GMT-05:00) Central Daylight Time (America/Chicago)</label>
            </value>
            <value>
                <fullName>Pacific/Honolulu</fullName>
                <label>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Honolulu)</label>
            </value>
            <value>
                <fullName>America/Phoenix</fullName>
                <label>(GMT-07:00) Mountain Standard Time (America/Phoenix)</label>
            </value>
            <value>
                <fullName>Pacific/Pitcairn</fullName>
                <label>(GMT-08:00) Pitcairn Time (Pacific/Pitcairn)</label>
            </value>
            <value>
                <fullName>US/Alaska</fullName>
                <isActive>false</isActive>
                <label>US/Alaska</label>
            </value>
            <value>
                <fullName>US/Central</fullName>
                <isActive>false</isActive>
                <label>US/Central</label>
            </value>
            <value>
                <fullName>US/Eastern</fullName>
                <isActive>false</isActive>
                <label>US/Eastern</label>
            </value>
            <value>
                <fullName>US/Hawaii</fullName>
                <isActive>false</isActive>
                <label>US/Hawaii</label>
            </value>
            <value>
                <fullName>US/Mountain</fullName>
                <isActive>false</isActive>
                <label>US/Mountain</label>
            </value>
            <value>
                <fullName>US/Pacific</fullName>
                <isActive>false</isActive>
                <label>US/Pacific</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/ZIP_Code__c.field-meta.xml
<CustomField>
    <fullName>ZIP_Code__c</fullName>
    <label>ZIP Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/compliancestatus__c.field-meta.xml
<CustomField>
    <fullName>compliancestatus__c</fullName>
    <label>compliance status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No – Vehicle Age</fullName>
            </value>
            <value>
                <fullName>No – Vehicle Value</fullName>
            </value>
            <value>
                <fullName>No – Insurance not meeting minimum</fullName>
            </value>
            <value>
                <fullName>Resubmit Insurance – you submitted an insurance card</fullName>
            </value>
            <value>
                <fullName>No - Insurance not provided</fullName>
            </value>
            <value>
                <fullName>No Compliance</fullName>
            </value>
            <value>
                <fullName>Resubmit - Expired Insurance</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <isActive>false</isActive>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivated_Date__c</fullName>
    <inlineHelpText>Date employee is deactivated. They will receive the fixed and last months variable.</inlineHelpText>
    <label>Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Driving_States__c.field-meta.xml
<CustomField>
    <fullName>Driving_States__c</fullName>
    <label>Driving States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isCommunityUser__c.field-meta.xml
<CustomField>
    <fullName>isCommunityUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCommunityUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsCreatedFromCommunity__c.field-meta.xml
<CustomField>
    <fullName>IsCreatedFromCommunity__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This Field is used in RG_CreateNewUserPageClass for creating new user for community page</inlineHelpText>
    <label>IsCreatedFromCommunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Role__c</field>
            <operation>equals</operation>
            <value>Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Mileage_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Mileage_Limit__c</fullName>
    <inlineHelpText>Manager selects how many miles can be driven for auto approval.</inlineHelpText>
    <label>Monthly Mileage Limit</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Triplog_UserID__c.field-meta.xml
<CustomField>
    <fullName>Triplog_UserID__c</fullName>
    <label>Triplog UserID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <description>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</description>
    <inlineHelpText>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</inlineHelpText>
    <label>Standard Vehicle Make Model and Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IRS_Mileage_Rate__c/IRS_Mileage_Rate__c.object-meta.xml
<CustomObject>
    <label>IRS Mileage Rate</label>
    <nameField>
        <displayFormat>IRS Rate-{0000}</displayFormat>
        <label>IRS Mileage Rate No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IRS Mileage Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IRS_Mileage_Rate__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>Year</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendEmail__c/SendEmail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Send Email</label>
</CustomObject>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/TriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TriggerConfig:- MappingGasPriceTrigger</description>
    <label>TriggerConfig</label>
</CustomObject>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriCommunityReimCreate__c.field-meta.xml
<CustomField>
    <fullName>ContactTriCommunityReimCreate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>ContactTriCommunityReimCreate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriggersendEmailForNewContact__c.field-meta.xml
<CustomField>
    <fullName>ContactTriggersendEmailForNewContact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use in contact trigger helper class for sendEmailForNewContact method.</description>
    <label>ContactTriggersendEmailForNewContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/Vehicle_URL_Mapping__c.object-meta.xml
<CustomObject>
    <label>Vehicle URL Mapping</label>
    <nameField>
        <label>Vehicle URL Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle URL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHelperTest.cls
@isTest
public class ContactTriggerHelperTest {
    static testMethod void sendEmailOnDriverCreateTest() {
        //Insert Custom setting data
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        customEmailSetting.ContactTriCommunityReimCreate__c = true;
        insert customEmailSetting;
        
        List<IRS_Mileage_Rate__c> obj_IRS_Mileage_Rate =  RecordUtilityClass.insertIrsRate();
         
        Address__c obj_Address = new Address__c();
        obj_Address.State__c ='Alabama';
        obj_Address.City__c ='Abbeville';
        obj_Address.Abbreviation__c ='AL';
        obj_Address.ZIP_Code__c ='36310'; 
        obj_Address.Time_Zone__c = 'America/Anchorage';
        List<Address__c> obj_list_Address = new List<Address__c>();
        obj_list_Address.add(obj_Address);
        insert obj_list_Address;

        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh.vehicle__c = 'Full-Size Sedan';
        veh.Year__c = '2019';
        insert veh;

        Vehicle_URL_Mapping__c veh2 = new Vehicle_URL_Mapping__c();
        veh2.URL__c = 'https://cdn3.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh2.vehicle__c = 'Dodge Charger';
        veh2.Year__c = '2020';
        insert veh2;
        
        SendEmail__c customSetting =  new SendEmail__c();
        customSetting.Name = 'Send Email For Compliance';
        customSetting.Send_email_from_code__c= true;
        insert customSetting;
         
        //Insert Account data Using Utility class
        Account acc = TestUtilityClass.getTestSingleAccount();
		acc.Triplog_API__c = 'fde76cdde14449bea46b321225ac8fd1';
		update acc;
        
        Contact con2 = new Contact();
        con2.FirstName = 'Test2';
        con2.LastName = 'Contact';
        con2.AccountId = acc.Id;
        con2.MailingStreet = 'Test Street';
        con2.MailingCity = 'Abbeville';
        con2.MailingState = 'AL';
        con2.MailingPostalCode = '123';
        con2.MailingCountry = 'CA';
        con2.Phone = '1232434445';
        con2.External_Email__c = 'minkesh.patel14@gmail.com';
        con2.Deactivated_Date__c = Null;
        con2.isCommunityUser__c = True;
		con2.Triplog_UserID__c = '23rcdsf';
        con2.Role__c = 'Manager';
        con2.Monthly_Mileage_Limit__c = 0;
        con2.IsCreatedFromCommunity__c = true; 
        insert con2;
        
        //Insert Contact data 
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc.Id;
        con.Fixed_Amount__c = 10;
        con.MailingStreet = 'Test Street';
        con.MailingCity = 'Test City';
        con.MailingState = 'AL';
		con.Triplog_UserID__c = '23rcdssf';
        con.MailingPostalCode = '36310';
        con.Manager__c = con2.Id;
        con.MailingCountry = 'CA';
        con.Phone = '1232434445';
        con.External_Email__c = 'minkesh.patel14232378@gmail.com';
        con.Deactivated_Date__c = system.today();
        con.isCommunityUser__c = True;
        con.Role__c = 'Driver';
        con.Monthly_Mileage_Limit__c = 0;
        con.IsCreatedFromCommunity__c = true; 
        con.Vehicle_Type__c  = '2019 Full-Size Sedan';
        con.compliancestatus__c = 'Yes';
        insert con;
        
        con.Deactivated_Date__c = null;
        con.compliancestatus__c = 'No – Vehicle Age';
        update con;
        
        Contact con1 = new Contact();
        con1.FirstName = 'Test2';
        con1.LastName = 'Contact2';
        con1.AccountId = acc.Id;
        con1.Fixed_Amount__c = 10;
        con1.MailingStreet = 'Test Street';
        con1.MailingCity = 'Test City';
        con1.MailingState = 'AL';
        con1.MailingPostalCode = '36310';
        con1.Manager__c = con2.Id;
        con1.MailingCountry = 'CA';
        con1.Phone = '1232434445';
		con1.Triplog_UserID__c = '23rcdsf';
        con1.External_Email__c = 'minkesh33.patel14232378@gmail.com';
        con1.Deactivated_Date__c = system.today();
        con1.isCommunityUser__c = True;
        con1.Role__c = 'Driver';
        con1.Monthly_Mileage_Limit__c = 0;
        con1.IsCreatedFromCommunity__c = true; 
        con1.Vehicle_Type__c  = '2019 Full-Size Sedan';
        con1.compliancestatus__c = 'No – Vehicle Age';
        insert con1;
        
        con1.compliancestatus__c = 'Yes';
		update con1;
        Map<String,String> contactInfo = new Map<String,String>();
        Map<String,String> accountInfo = new Map<String,String>();
        contactInfo.put(con1.Triplog_UserID__c, con1.Phone);
        accountInfo.put(con1.Triplog_UserID__c, acc.Triplog_API__c);
        ContactTriggerHelper.putHTTPEnableUserTriplog(con1.Id);
        ContactTriggerHelper.putHTTPUpdateUserPhoneTriplog(contactInfo,accountInfo);
        
    }
    static testMethod void testmethod3() {
        //Insert Custom setting data
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        customEmailSetting.ContactTriCommunityReimCreate__c = true;
        insert customEmailSetting;
        
        List<IRS_Mileage_Rate__c> obj_IRS_Mileage_Rate =  RecordUtilityClass.insertIrsRate();
         
        Address__c obj_Address1 = new Address__c();
        obj_Address1.State__c ='Alabama';
        obj_Address1.City__c ='Abbeville';
        obj_Address1.Abbreviation__c ='AL';
        obj_Address1.ZIP_Code__c ='36310'; 
        obj_Address1.Time_Zone__c = 'America/Anchorage';
        
        Address__c obj_Address = new Address__c(); 
        obj_Address.State__c ='kabila';
        obj_Address.City__c ='Abbeville';
        obj_Address.Abbreviation__c ='AK';
        obj_Address.ZIP_Code__c ='36311'; 
        obj_Address.Time_Zone__c = 'America/Anchorage';
        List<Address__c> obj_list_Address = new List<Address__c>();
        obj_list_Address.add(obj_Address);
        obj_list_Address.add(obj_Address1);
        insert obj_list_Address;

        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh.vehicle__c = 'Full-Size Sedan';
        veh.Year__c = '2019';
        insert veh;

        Vehicle_URL_Mapping__c veh2 = new Vehicle_URL_Mapping__c();
        veh2.URL__c = 'https://cdn3.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh2.vehicle__c = 'Dodge Charger';
        veh2.Year__c = '2020';
        insert veh2;
        
        SendEmail__c customSetting =  new SendEmail__c();
        customSetting.Name = 'Send Email For Compliance';
        customSetting.Send_email_from_code__c= true;
        insert customSetting;
         
        //Insert Account data Using Utility class
        Account acc = TestUtilityClass.getTestSingleAccount();

        Contact con2 = new Contact();
        con2.FirstName = 'Test2';
        con2.LastName = 'Contact';
        con2.AccountId = acc.Id;
        con2.MailingStreet = 'Test Street';
        con2.MailingCity = 'Abbeville';
        con2.MailingState = 'AL';
        con2.MailingPostalCode = '123';
        con2.MailingCountry = 'CA';
        con2.Phone = '1232434445';
        con2.External_Email__c = 'minkesh.patel14@gmail.com';
        con2.Deactivated_Date__c = Null;
        con2.isCommunityUser__c = True;
        con2.Role__c = 'Manager';
        con2.Monthly_Mileage_Limit__c = 0;
        con2.IsCreatedFromCommunity__c = true; 
        
        
        insert con2;
        
        //Insert Contact data 
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc.Id;
        con.Fixed_Amount__c = 10;
        con.MailingStreet = 'Test Street';
        con.MailingCity = 'Test City';
        con.MailingState = null;
        con.MailingPostalCode = '36310';
        con.Manager__c = con2.Id;
        con.MailingCountry = 'CA';
        con.Phone = '1232434445';
        con.External_Email__c = 'minkesh.patel14232378@gmail.com';
        con.Deactivated_Date__c = Null;
        con.isCommunityUser__c = True;
        con.Role__c = 'Driver';
        con.Triplog_UserID__c = '370415';
        con.Monthly_Mileage_Limit__c = 0;
        con.IsCreatedFromCommunity__c = true; 
        con.Vehicle_Type__c  = '2019 Full-Size Sedan';
        con.compliancestatus__c = 'No – Vehicle Value';
        con.Driving_States__c = 'AL';
        insert con;
        
        con.compliancestatus__c = 'No – Insurance not meeting minimum';      
        con.Phone = '24777';
        update con;
    }
    static testMethod void testmethod4() {
        //Insert Custom setting data
        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        customEmailSetting.ContactTriCommunityReimCreate__c = true;
        insert customEmailSetting;
        
        List<IRS_Mileage_Rate__c> obj_IRS_Mileage_Rate =  RecordUtilityClass.insertIrsRate();
         
        Address__c obj_Address1 = new Address__c();
        obj_Address1.State__c ='Alabama';
        obj_Address1.City__c ='Abbeville';
        obj_Address1.Abbreviation__c ='AL';
        obj_Address1.ZIP_Code__c ='36310'; 
        obj_Address1.Time_Zone__c = 'America/Anchorage';
        
        Address__c obj_Address = new Address__c(); 
        obj_Address.State__c ='kabila';
        obj_Address.City__c ='Abbeville';
        obj_Address.Abbreviation__c ='AK';
        obj_Address.ZIP_Code__c ='36311'; 
        obj_Address.Time_Zone__c = 'America/Anchorage';
        List<Address__c> obj_list_Address = new List<Address__c>();
        obj_list_Address.add(obj_Address);
        obj_list_Address.add(obj_Address1);
        insert obj_list_Address;

        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh.vehicle__c = 'Full-Size Sedan';
        veh.Year__c = '2019';
        insert veh;

        Vehicle_URL_Mapping__c veh2 = new Vehicle_URL_Mapping__c();
        veh2.URL__c = 'https://cdn3.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh2.vehicle__c = 'Dodge Charger';
        veh2.Year__c = '2020';
        insert veh2;
        
        SendEmail__c customSetting =  new SendEmail__c();
        customSetting.Name = 'Send Email For Compliance';
        customSetting.Send_email_from_code__c= true;
        insert customSetting;
         
        //Insert Account data Using Utility class
        Account acc = TestUtilityClass.getTestSingleAccount();

        Contact con2 = new Contact();
        con2.FirstName = 'Test2';
        con2.LastName = 'Contact';
        con2.AccountId = acc.Id;
        con2.MailingStreet = 'Test Street';
        con2.MailingCity = 'Abbeville';
        con2.MailingState = 'AL';
        con2.MailingPostalCode = '123';
        con2.MailingCountry = 'CA';
        con2.Phone = '1232434445';
        con2.External_Email__c = 'minkesh.patel14@gmail.com';
        con2.Deactivated_Date__c = Null;
        con2.isCommunityUser__c = True;
        con2.Role__c = 'Manager';
        con2.Monthly_Mileage_Limit__c = 0;
        con2.IsCreatedFromCommunity__c = true; 
        
        
        insert con2;
        
        //Insert Contact data 
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.AccountId = acc.Id;
        con.Fixed_Amount__c = 10;
        con.MailingStreet = 'Test Street';
        con.MailingCity = 'Test City';
        con.MailingState = null;
        con.MailingPostalCode = '36310';
        con.Manager__c = con2.Id;
        con.MailingCountry = 'CA';
        con.Phone = '1232434445';
        con.External_Email__c = 'minkesh.patel14232378@gmail.com';
        con.Deactivated_Date__c = Null;
        con.isCommunityUser__c = True;
        con.Role__c = 'Driver';
        con.Monthly_Mileage_Limit__c = 0;
        con.IsCreatedFromCommunity__c = true; 
        con.Vehicle_Type__c  = '2019 Full-Size Sedan';
        con.compliancestatus__c = 'No – Vehicle Value';
        con.Driving_States__c = 'AL';
        insert con;
        
        con.compliancestatus__c = 'Yes';        
        update con;
    }
   
}