force-app/main/default/objects/Account/fields/Triplog_API__c.field-meta.xml
<CustomField>
    <fullName>Triplog_API__c</fullName>
    <label>Triplog API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Mileage_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Mileage_Limit__c</fullName>
    <inlineHelpText>Manager selects how many miles can be driven for auto approval.</inlineHelpText>
    <label>Monthly Mileage Limit</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/FromLocationId__c.field-meta.xml
<CustomField>
    <fullName>FromLocationId__c</fullName>
    <label>FromLocationId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Rejected__c.field-meta.xml
<CustomField>
    <fullName>Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Reject trip record</inlineHelpText>
    <label>Rejected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/ToLocationId__c.field-meta.xml
<CustomField>
    <fullName>ToLocationId__c</fullName>
    <label>ToLocationId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Id__c.field-meta.xml
<CustomField>
    <fullName>Trip_Id__c</fullName>
    <externalId>true</externalId>
    <label>Trip Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Status__c</fullName>
    <label>Trip Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Approved Yet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/TriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TriggerConfig:- MappingGasPriceTrigger</description>
    <label>TriggerConfig</label>
</CustomObject>

force-app/main/default/objects/TriggerConfig__c/fields/mileageremoveapprovaldate__c.field-meta.xml
<CustomField>
    <fullName>mileageremoveapprovaldate__c</fullName>
    <defaultValue>true</defaultValue>
    <label>mileageremoveapprovaldate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LoadMileageLocationBatchTest.cls
@isTest
public with sharing class LoadMileageLocationBatchTest {   
    static testMethod void loadTestMethod() {
        RecordUtilityClass.createRecordsAdminDashboardController();
            Test.setMock(HttpCalloutMock.class, new LoadMileageLocationBatchTestMock());
            Account currentAccount = RecordUtilityClass.getAccount(); // retriving the Accounts EmployeeMileagesForCalculation
            Contact currentAdmin = RecordUtilityClass.getAdminContact(); // Retriving the Admin with limit 1
            Contact selectedDriver = RecordUtilityClass.getDriverContact();
           
            List<Employee_Reimbursement__c> empReimbursementList = RecordUtilityClass.getEmployee_Reimbursement(currentAccount.id);
            List<EmployeeReimbursementDetailsAdmin> selectedReimList = RecordUtilityClass.getListofEmployeeReimbursementDetailsAdmin(empReimbursementList);
            List<Employee_Mileage__c> driverMileagesList =  RecordUtilityClass.getMileagesList();
            driverMileagesList[0].Trip_Id__c = 104976448;
            update driverMileagesList;
            
        String json = '{'+
        '    \"message\": \"OK\",'+
        '    \"location\": {'+
        '        \"id\": 143316643,'+
        '        \"url\": \"https://triplogmileage.com/web/api/locations/143316643\",'+
        '        \"lastUpdated\": \"2020-04-01T19:32:17.753Z\",'+
        '        \"display\": \"33.182021,-96.748293\",'+
        '        \"name\": null,'+
        '        \"address\": null,'+
        '        \"latitude\": 33.182021,'+
        '        \"longitude\": -96.748293,'+
        '        \"accuracy\": 5,'+
        '        \"defaultActivity\": null'+
        '    }'+
        '}';
        
        Test.StartTest();  
        LoadMileageLocationBatch batchobj = new LoadMileageLocationBatch(new Set<Id>{empReimbursementList[0].Id}, true);
        Database.executeBatch(batchobj,10);
        Test.StopTest();

    }

    static testMethod void loadTestMethod2() {
        RecordUtilityClass.createRecordsAdminDashboardController();
            Test.setMock(HttpCalloutMock.class, new LoadMileageLocationBatchTestMock());
            Account currentAccount = RecordUtilityClass.getAccount(); // retriving the Accounts EmployeeMileagesForCalculation
            Contact currentAdmin = RecordUtilityClass.getAdminContact(); // Retriving the Admin with limit 1
            Contact selectedDriver = RecordUtilityClass.getDriverContact();
           
            List<Employee_Reimbursement__c> empReimbursementList = RecordUtilityClass.getEmployee_Reimbursement(currentAccount.id);
            List<EmployeeReimbursementDetailsAdmin> selectedReimList = RecordUtilityClass.getListofEmployeeReimbursementDetailsAdmin(empReimbursementList);
            List<Employee_Mileage__c> driverMileagesList =  RecordUtilityClass.getMileagesList();
            driverMileagesList[0].Trip_Id__c = 104976448;
            update driverMileagesList;

            Set<Id> mileagesIdSet = new Set<Id>();
            for(Employee_Mileage__c empRei:driverMileagesList){
                mileagesIdSet.add(empRei.Id);
            }

            Test.StartTest();
            LoadMileageLocationBatch batchobj = new LoadMileageLocationBatch(mileagesIdSet, false);
            Database.executeBatch(batchobj,10);
            Test.StopTest();

    }

    static testMethod void loadTestMethod3() {
 
        Test.setMock(HttpCalloutMock.class, new LoadMileageLocationBatchTestMock());

        TriggerConfig__c customSetting =  new TriggerConfig__c();
        customSetting.Name = 'Defaulttrigger';
        customSetting.mileageremoveapprovaldate__c = false;
        insert customSetting;

        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Triplog_API__c = 'isduif388';
        insert acc;

        Contact con = new Contact();
        con.FirstName = 'FirstCont';
        con.LastName = 'TestContact';
        con.AccountId = acc.Id;
        con.External_Email__c = 'test@email.com';
        con.Fixed_Amount__c = 371.28;
        con.MailingCity = 'Fremont';
        con.MailingState = 'CA';        
        con.Monthly_Mileage_Limit__c = 100.00;
        insert con;

        Employee_Reimbursement__c er = new Employee_Reimbursement__c();
        er.Contact_Id__c = con.Id;
        er.Name = 'Reimbersment Test';
        er.Month__c = '03-2020';
        er.Status__c = 'Pending';
        insert er;

        Employee_Mileage__c emp = new Employee_Mileage__c();
        emp.EmployeeReimbursement__c = er.id;
        emp.Contact_Email_Id__c = con.External_Email__c;
        emp.Name = 'Test Mileage Record';
        emp.Trip_Status__c = StaticValues.noApprovedYet;
        emp.Rejected__c = true;
        emp.Mileage__c = 150.00;
        emp.FromLocationId__c = 5767;
        emp.ToLocationId__c = 23235;
        insert emp;
        
        Test.StartTest();
        LoadMileageLocationBatch batchobj = new LoadMileageLocationBatch();
        Database.executeBatch(batchobj,10);
        Test.StopTest();
    }
}