force-app/main/default/objects/Account/fields/Triplog_API__c.field-meta.xml
<CustomField>
    <fullName>Triplog_API__c</fullName>
    <label>Triplog API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Triplog_Status__c.field-meta.xml
<CustomField>
    <fullName>Triplog_Status__c</fullName>
    <inlineHelpText>U - Not submitted
S - Submitted
A - Approved
R - Rejected
P - Pay scheduled</inlineHelpText>
    <label>Triplog Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U</fullName>
                <default>true</default>
                <label>U</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/isCommunityUser__c.field-meta.xml
<CustomField>
    <fullName>isCommunityUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCommunityUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>10</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Triplog_Status__c.field-meta.xml
<CustomField>
    <fullName>Triplog_Status__c</fullName>
    <inlineHelpText>U - Not submitted 
S - Submitted 
A - Approved 
R - Rejected 
P - Pay scheduled</inlineHelpText>
    <label>Triplog Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U</fullName>
                <default>true</default>
                <label>U</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <description>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</description>
    <inlineHelpText>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</inlineHelpText>
    <label>Standard Vehicle Make Model and Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Fuel_price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_price__c</fullName>
    <label>Fuel price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Triplog_Status__c.field-meta.xml
<CustomField>
    <fullName>Triplog_Status__c</fullName>
    <inlineHelpText>U - Not submitted 
S - Submitted 
A - Approved 
R - Rejected 
P - Pay scheduled</inlineHelpText>
    <label>Triplog Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U</fullName>
                <default>true</default>
                <label>U</label>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>VALUE(RIGHT(Month__c,Find(&quot;-&quot;, Month__c)+1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Get_Trip_Date_Settings__c/Get_Trip_Date_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Date Settings :- Example yyyy-mm-dd  2018-07-31 and Last N days If Current month is Aug and you want july data then you can have last 30 days for deactivation date.
if Current month is Aug and you want to Get June reimbersment then you need to put 60</description>
    <label>Get Trip Date Settings</label>
</CustomObject>

force-app/main/default/objects/Get_Trip_Date_Settings__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Get_Trip_Date_Settings__c/fields/Last_N_Days__c.field-meta.xml
<CustomField>
    <fullName>Last_N_Days__c</fullName>
    <label>Last N Days</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Get_Trip_Date_Settings__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendEmail__c/SendEmail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Send Email</label>
</CustomObject>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailToMe__c/SendEmailToMe__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SendEmailToMe</label>
</CustomObject>

force-app/main/default/objects/SendEmailToMe__c/fields/Send_email_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_email_to_me__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send email to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/TriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TriggerConfig:- MappingGasPriceTrigger</description>
    <label>TriggerConfig</label>
</CustomObject>

force-app/main/default/objects/TriggerConfig__c/fields/MappingGasPriceTrigger__c.field-meta.xml
<CustomField>
    <fullName>MappingGasPriceTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <description>MappingGasPriceTrigger</description>
    <inlineHelpText>MappingGasPriceTrigger</inlineHelpText>
    <label>MappingGasPriceTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/Vehicle_URL_Mapping__c.object-meta.xml
<CustomObject>
    <label>Vehicle URL Mapping</label>
    <nameField>
        <label>Vehicle URL Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle URL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GetDailyTripsFromTriplogTest.cls
@isTest
public with sharing class GetDailyTripsFromTriplogTest {
    public static testmethod void GetTriptest() {
        List<Id> contactids = new List<Id>();
        Map<Id, Employee_Reimbursement__c> conReim = new Map<Id, Employee_Reimbursement__c>();
        
        TriggerConfig__c customSetting =  new TriggerConfig__c();
        customSetting.Name = 'Defaulttrigger';
        customSetting.MappingGasPriceTrigger__c = true;
        insert customSetting;
        
        SendEmailToMe__c sendEmail = new SendEmailToMe__c();
        sendEmail.Name = 'GetTripCallOutApprovePutCall';
        sendEmail.Send_email_to_me__c = true;
        insert sendEmail;
        
        SendEmail__c customSetting1 =  new SendEmail__c();
        customSetting1.Name = 'Send Email For Compliance';
        customSetting1.Send_email_from_code__c= true;
        insert customSetting1;
        
        Get_Trip_Date_Settings__c obj_Get_Trip_Date_Settings = new Get_Trip_Date_Settings__c();
        obj_Get_Trip_Date_Settings.Name ='Date Settings';
        obj_Get_Trip_Date_Settings.Start_Date__c ='2020-08-01';
        obj_Get_Trip_Date_Settings.End_Date__c ='2020-08-31';
        obj_Get_Trip_Date_Settings.Last_N_Days__c ='31';
        insert obj_Get_Trip_Date_Settings;
        
        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh.vehicle__c = 'Mileage Rate';
        veh.Year__c = '2019';
        insert veh;
        
        Account acc = new Account();           
        acc.Name = 'Delta account';
        acc.Triplog_API__c = '123456789';
        Acc.Triplog_Status__c = 'U';
        insert Acc;
        
        Contact contact = new Contact();
        contact.lastname = 'Test Contact';
        contact.AccountId = Acc.Id;
        contact.External_Email__c = 'minkesh.patel1478@gmail.com';
        contact.Email = 'minkesh.patel1478@gmail.com';
        contact.isCommunityUser__c = true;
        contact.MailingCity='ahmedabad';
        contact.Vehicle_Type__c = '2019 Mileage Rate';
        contact.MailingState='GJ';
        insert contact;
        contactids.add(contact.Id);
        
        Contact con = new Contact();
        con.lastname = 'Test Con';
        con.AccountId = Acc.Id;
        con.External_Email__c = 'minkesh.patel1357@gmail.com';
        con.Email = 'minkesh.patel1357@gmail.com';
        con.Triplog_Status__c = 'U';
        con.Vehicle_Type__c = '2019 Mileage Rate';
        con.isCommunityUser__c = true;
        insert con;
        contactids.add(con.Id);
        
        Employee_Reimbursement__c er = new Employee_Reimbursement__c();
        er.Contact_Id__c = contact.Id;
        
        er.month__c = '08-2020';
        er.Name = contact.lastname+':'+er.month__c;
        er.Status__c = 'Pending';
        er.Fuel_Price__c = 1;  //String.valueof(er.Fuel_Price__c); // 
        er.MPG__c = 10.00;
        er.Maintenance_and_Tires__c = 24;//String.valueof(er.Maintenance_and_Tires__c);
        er.Fuel_Price__c = 1;
        er.MPG__c = 10;
        er.Maintenance_and_Tires__c = 10;
        er.Fixed_Amount__c = 10.10;
        er.Triplog_Status__c = 'U';
        insert er;
        conReim.put(con.Id,er);
        
        Employee_Mileage__c emp = new Employee_Mileage__c();
        emp.Contact_Email_Id__c = 'test@test.gmail.com';
        emp.Name = 'Test Mileage Record';
        emp.EmployeeReimbursement__c = er.id;
        insert emp;
        
        Test.startTest();
        Test.SetMock(HttpCalloutMock.class, new GetTripCalloutMock());
        GetDailyTripsFromTriplog obj = new GetDailyTripsFromTriplog('U');
        DataBase.executeBatch(obj);
        
        Test.stopTest();
    }
}