force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Contact_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email_Id__c</fullName>
    <label>Contact Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Day_Of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_Of_Week__c</fullName>
    <label>Day Of Week</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Destination_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Name__c</fullName>
    <description>Destination Name</description>
    <inlineHelpText>Destination Name</inlineHelpText>
    <label>Destination Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End date and time of the trips.</description>
    <label>EndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/FromLocationId__c.field-meta.xml
<CustomField>
    <fullName>FromLocationId__c</fullName>
    <label>FromLocationId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Fuel_price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_price__c</fullName>
    <label>Fuel price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Notes 131,072</description>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Origin_Name__c.field-meta.xml
<CustomField>
    <fullName>Origin_Name__c</fullName>
    <description>Origin Name</description>
    <inlineHelpText>Origin Name</inlineHelpText>
    <label>Origin Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start date and time of the trips.</description>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Stay_Time__c.field-meta.xml
<CustomField>
    <fullName>Stay_Time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stay Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <label>Tag</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/ToLocationId__c.field-meta.xml
<CustomField>
    <fullName>ToLocationId__c</fullName>
    <label>ToLocationId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Tracing_Style__c.field-meta.xml
<CustomField>
    <fullName>Tracing_Style__c</fullName>
    <description>Tracking method for the trips.</description>
    <label>Tracing Style</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Destination__c.field-meta.xml
<CustomField>
    <fullName>Trip_Destination__c</fullName>
    <label>Trip Destination</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Id__c.field-meta.xml
<CustomField>
    <fullName>Trip_Id__c</fullName>
    <externalId>true</externalId>
    <label>Trip Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Origin__c.field-meta.xml
<CustomField>
    <fullName>Trip_Origin__c</fullName>
    <label>Trip Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Status__c</fullName>
    <label>Trip Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Approved Yet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Triplog_Map__c.field-meta.xml
<CustomField>
    <fullName>Triplog_Map__c</fullName>
    <label>Triplog Map</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Maintenance_and_Tires__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_and_Tires__c</fullName>
    <label>Maintenance and Tires</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/MPG__c.field-meta.xml
<CustomField>
    <fullName>MPG__c</fullName>
    <label>MPG</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SendEmailToMe__c/SendEmailToMe__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SendEmailToMe</label>
</CustomObject>

force-app/main/default/objects/SendEmailToMe__c/fields/Send_email_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_email_to_me__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send email to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/Tripslog__c.object-meta.xml
<CustomObject>
    <label>Tripslog</label>
    <nameField>
        <displayFormat>Tripno-{0000000}</displayFormat>
        <label>Triplog No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tripslogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tripslog__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tripslogs</relationshipLabel>
    <relationshipName>Tripslogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Employee_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Reimbursement</description>
    <inlineHelpText>Employee Reimbursement</inlineHelpText>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Tripslogs</relationshipLabel>
    <relationshipName>Tripslogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint</description>
    <inlineHelpText>Endpoint</inlineHelpText>
    <label>Endpoint</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Response</description>
    <inlineHelpText>Response</inlineHelpText>
    <label>Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>200 is Success and others are Fail</description>
    <inlineHelpText>200 is Success and others are Fail</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Total_Mileages__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileages__c</fullName>
    <label>Total Mileages</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Total_Trips__c.field-meta.xml
<CustomField>
    <fullName>Total_Trips__c</fullName>
    <label>Total Trips</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GetTripCallout.cls
/*
 * @Author:  GetonCRM Solutions LLP
 * @Description:  Webservice class to fetch Mileages of contacts from TripLog 
 * ------------------------------------------------------------------------------------------------------------------------
 * @Modification Logs
 * ------------------------------------------------------------------------------------------------------------------------
 * @version 1.1   - @Author:  Sanjay Halpati - 12 May 2020
 * @Description: Added MLOGACCOUNT to Identify new MLOG API accounts for fetching Trips
 * Added a boolean variable for put call on 09/07/2020
 */
global class GetTripCallout {
    
    public static final String MLOGACCOUNT = System.Label.Triplog_New_URL; 
    
    Webservice static void GetTripCalloutForMileage(ID empReID, String contactEmail, ID contactid, String priMin, String priMax, String fuel, String mpg, String maintenansAndTires, String apiToken, String tripStatus,Boolean putCall) 
    {
        List<Tripslog__c> obj_Tripslog_list = new List<Tripslog__c>();   
        List<Employee_Mileage__c> empList = new List<Employee_Mileage__c>();
        Double totalmileages = 0;
        
        //Request Variables
        Http h = new Http();
        HttpRequest req = new HttpRequest();

        // MLOG URL Change | Sanjay Halpati | 12 May 2020 | START
        String endPoint = 'startDate=' + priMin + '&userEmail=' + contactEmail + '&endDate=' + priMax + '&status=' + 
                    tripStatus + '&activity=Business';
        String baseURL = !MLOGACCOUNT.Contains(apiToken) ? StaticValues.TRIPLOG_BASEURL : StaticValues.MLOG_BASEURL;

        req.setEndpoint(baseURL + StaticValues.GETTRIP_SUFFIX + endPoint );
        // MLOG URL Change | Sanjay Halpati | 12 May 2020 | END

        req.setMethod('GET');
        req.setTimeout(120000);
        req.setHeader('Authorization', 'apikey ' + apiToken);
        HttpResponse res = h.send(req);

        Set<Integer> trip_IDs = new Set<Integer>();
        String empMilName = String.valueOf(empReID).substring(0, 15);
        Integer index = 0;
        if(res.getStatusCode() == 200) {                
            TripLogJSONClass.TripLogJSONClassInner tripLog = TripLogJSONClass.parse(res.getBody());
            List<TripLogJSONClass.Trips> listTrips = tripLog.trips;
            Datetime MaxTime;
            /**** Create Employee Mileage Record ****/
            for(TripLogJSONClass.Trips lt : listTrips) 
            {   
                Employee_Mileage__c emp = new Employee_Mileage__c();
                emp.Name = 'EMP-' + empMilName + index;
                emp.Trip_Status__c = StaticValues.noApprovedYet;
                emp.Trip_Id__c = lt.id;
                emp.Mileage__c = lt.mileage;
                //AI-000408
                /*if(emp.Mileage__c == null || emp.Mileage__c == 0) {
                    emp.Trip_Status__c = 'Approved';
                    emp.Approved_Date__c = System.Today();
                }*/
                emp.EmployeeReimbursement__c = empReID;
                emp.Contact_Email_Id__c = contactEmail;
                emp.StartTime__c = !CheckNull(lt.startTime) ? ConvertToDateTime(lt.startTime) : null;
                emp.Day_Of_Week__c = !CheckNull(lt.startTime) ? emp.StartTime__c.format('EEEE') : null;
                emp.EndTime__c = !CheckNull(lt.endTime) ? ConvertToDateTime(lt.endTime) : null;
                emp.Fuel_price__c = !CheckNull(fuel) ? Decimal.valueof(fuel) : null;
                emp.MPG__c = !CheckNull(mpg) ? Decimal.valueof(mpg) : null;
                emp.Maintenance_and_Tires__c = !CheckNull(maintenansAndTires) ? Decimal.valueof(maintenansAndTires) : null;

                
                if(lt.fromLocation != null && lt.fromLocation.display != null ) {
                    emp.FromLocationId__c = lt.fromLocation.id;
                    emp.Trip_Origin__c = lt.fromLocation.display;
                    if(lt.fromLocation.display.contains(',')) {
                        emp.Origin_Name__c = (lt.fromLocation.display.split(','))[0];  
                    } else if(lt.fromLocation.display.contains(' ')) {
                        emp.Origin_Name__c = (lt.fromLocation.display.split(' '))[0];
                    } else {
                        emp.Origin_Name__c =  lt.fromLocation.display;
                    }
                }
                if(lt.toLocation != null && lt.toLocation.display != null) {
                    emp.ToLocationId__c = lt.toLocation.id;
                    emp.Trip_Destination__c = lt.toLocation.display;
                    if(lt.toLocation.display.contains(',')) {
                        emp.Destination_Name__c = (lt.toLocation.display.split(','))[0];  
                    } else if(lt.toLocation.display.contains(' ')) {
                        emp.Destination_Name__c = (lt.toLocation.display.split(' '))[0];
                    } else {
                        emp.Destination_Name__c =  lt.toLocation.display;
                    }
                }

                emp.Notes__c = !CheckNull(lt.notes) ? lt.notes : null;
                emp.Tracing_Style__c = !CheckNull(lt.trackingMethod) ? lt.trackingMethod : null;
                emp.Tag__c = !CheckNull(lt.tags) ? lt.tags : null;
                emp.Stay_Time__c = !CheckNull(String.valueOf(lt.stayTimeMins)) ? lt.stayTimeMins : null;
                /*if( MaxTime != null && emp.StartTime__c.day() > MaxTime.day() && !empList.isEmpty()){
                    empList.get(empList.size()-1).Stay_Time__c = 0;
                }
                MaxTime = emp.EndTime__c;*/
                if(!CheckNull(lt.map_Z)){
                    emp.Triplog_Map__c = baseURL + '/kml/embed/' +  ( lt.map_Z.contains('/') ? lt.map_Z.split('/')[4] : ''); // MLOG Change | Sanjay Halpati | 12 May 2020
                } else {
                    emp.Triplog_Map__c = null;
                }

                emp.Trip_Date__c = !CheckNull(lt.startTime) ? Date.valueof(lt.startTime.split('T')[0]) : null;
                empList.add(emp);
                trip_IDs.add(Integer.valueOf(lt.id));
                totalmileages += Double.valueOf(emp.Mileage__c);    
                index ++;                
            }

            Integer successCount = 0;
            if(!empList.isEmpty()) {
                SendEmailToMe__c objSendEmailToMe = SendEmailToMe__c.getValues('GetTripCallOutApprovePutCall');
                if(objSendEmailToMe.Send_email_to_me__c && putCall == true){
                    GetTripCallout.putHTTP(apiToken, contactid, empReID, trip_IDs); 
                }

                Database.UpsertResult[] insertedTrips = Database.upsert(empList,Employee_Mileage__c.Fields.Trip_Id__c, false);
                
                for(Database.UpsertResult srresult : insertedTrips) {
                    if(srresult.isSuccess())
                        successCount ++;
                }
               
            }
            Tripslog__c obj = new Tripslog__c();
            obj.Contact__c = contactid;
            obj.Employee_Reimbursement__c = empReID;
            obj.Endpoint__c = baseURL + StaticValues.GETTRIP_SUFFIX + endPoint;
            obj.Response__c = String.valueOf(res.getStatusCode())+' ### ' +res.getStatus();
            obj.Status__c ='Success'; 
            obj.Total_Trips__c= successCount;
            obj.Total_Mileages__c = totalmileages;
            obj_Tripslog_list.add(obj); 
        }
        else {
            Tripslog__c obj = new Tripslog__c();
            obj.Contact__c = contactid;
            obj.Employee_Reimbursement__c = empReID;
            obj.Endpoint__c = baseURL + StaticValues.GETTRIP_SUFFIX + endPoint;
            obj.Response__c = String.valueOf(res.getStatusCode())+' ### ' +res.getStatus();
            obj.Status__c ='Fail'; 
            obj.Total_Trips__c = 0;
            obj.Total_Mileages__c = 0;
            obj_Tripslog_list.add(obj); 
        }
        if(!obj_Tripslog_list.isEmpty()) {
            insert obj_Tripslog_list;
            
            if(!System.isBatch() ) {
                Database.executeBatch(new LoadMileageLocationBatch(new Set<Id>{ empReID }, true ),50);
            }
        }
    }

    public static void putHTTP(String apiToken,String contactid,String empReID, Set<Integer> trip_IDs) {
        
        List<Tripslog__c> obj_Tripslog_list = new List<Tripslog__c>();
        HttpRequest putReq = new HttpRequest();
        Http putHTTP = new Http();
        String body = '{"status":"Submitted","ids":[';
        String part = '';

        for (Integer i : trip_IDs) {
            part += String.valueof(i) + ',';
        }
        part = part.removeEnd(',');
        body += part +']}';
        String endPoint = !MLOGACCOUNT.Contains(apiToken) ? StaticValues.TRIPLOG_BASEURL : StaticValues.MLOG_BASEURL;
        endPoint += StaticValues.STATUS_SUFFIX;
        putReq.setEndpoint(endPoint);
        putReq.setMethod('PUT');                 
        putReq.setBody(body);
        putReq.setTimeout(120000);
        putReq.setHeader('Authorization', 'apikey ' + apiToken);
        HttpResponse putRes = putHTTP.send(putReq);

        Tripslog__c obj = new Tripslog__c();
        obj.Body__c = body;
        obj.Contact__c = contactid;
        obj.Employee_Reimbursement__c = empReID;
        obj.Endpoint__c = endPoint;
        if(!Test.IsRunningTest())
        {
            obj.Response__c = String.valueOf(putRes.getStatusCode()) + ' ######## ' + putRes.getStatus();
        }
        
        obj.Total_Trips__c= 0;
        obj.Total_Mileages__c = 0;
        obj.Status__c = putRes.getStatusCode() == 200 ? 'Success' : 'Fail';
        obj_Tripslog_list.add(obj);

        if(!obj_Tripslog_list.isEmpty()) {
            insert obj_Tripslog_list;
        }
    }

    public static Boolean CheckNull(String param1) {
        return param1 == null || param1 == '' ? true : false;
    }

    public Static DateTime ConvertToDateTime(String param1) {
        
        param1 = param1.replace(':','-');
        param1 = param1.replace('T','-');
        return DateTime.newInstance(
                Integer.valueof(param1.split('-')[0]), 
                Integer.valueof(param1.split('-')[1]), 
                Integer.valueof(param1.split('-')[2]), 
                Integer.valueof(param1.split('-')[3]), 
                Integer.valueof(param1.split('-')[4]), 
                Integer.valueof(param1.split('-')[5].removeEnd('.000Z'))
            );
    }
}