force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/ConvertedEndTime__c.field-meta.xml
<CustomField>
    <fullName>ConvertedEndTime__c</fullName>
    <label>ConvertedEndTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/ConvertedStartTime__c.field-meta.xml
<CustomField>
    <fullName>ConvertedStartTime__c</fullName>
    <label>ConvertedStartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Day_Of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_Of_Week__c</fullName>
    <label>Day Of Week</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Driving_Time__c.field-meta.xml
<CustomField>
    <fullName>Driving_Time__c</fullName>
    <formula>IF(!ISNULL(ConvertedEndTime__c)  &amp;&amp; !ISNULL(ConvertedStartTime__c) , (ConvertedEndTime__c - ConvertedStartTime__c )*24*60, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driving Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Origin_Name__c.field-meta.xml
<CustomField>
    <fullName>Origin_Name__c</fullName>
    <description>Origin Name</description>
    <inlineHelpText>Origin Name</inlineHelpText>
    <label>Origin Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Stay_Time__c.field-meta.xml
<CustomField>
    <fullName>Stay_Time__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Stay Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Total_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Time__c</fullName>
    <formula>Stay_Time__c + Driving_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimeandSummaryReportController.cls
/*
 * @Author:  GetonCRM Solutions LLP
 * @Description:  Apex class use to download a excel file for Time and Attendance Summary report.
 * ------------------------------------------------------------------------------------------------------------------------
 * @Modification Logs
 * ------------------------------------------------------------------------------------------------------------------------
 * @version 1.1   - @Author:  Sanket Goswami - 1 July 2020
 */
public with sharing class TimeandSummaryReportController {
    public List<mileageWrapper> mileageWrapperList{get;set;}
    public double totalMileges {get; set;}
    public string totalDriveTime {get; set;}
    public string totalStayTimeForMonth {get; set;}
    public string totalTimeForMonth {get; set;}
    public string contactName {get; set;}
    public integer totalMinute;
    public integer totalStay;
    public integer totalTimes;
    public String xlsHeader{
        get{
            String strHeader = '';
            strHeader += '<?xml version="1.0" encoding="UTF-8"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
    
        }
    
    }
    public TimeandSummaryReportController() {
        drivingTime();
    }
    public void drivingTime(){
        String Id = ApexPages.currentPage().getParameters().get('id');
        String startDate = ApexPages.currentPage().getParameters().get('startDate');
        String endDate = ApexPages.currentPage().getParameters().get('endDate');
        system.debug('id'+id+'startDate'+startDate+'endDate'+endDate);
        mileageWrapperList = new List<mileageWrapper>();
        Map<Date,String> tripdateDayMap = new Map<Date,String>(); 
        Map<Date,Double> tripdateMileageMap = new Map<Date,Double>();
        Map<Date,Decimal> tripdateDrivingTimeMap = new Map<Date,Decimal>();
        Map<Date,Decimal> tripStayTimeMap = new Map<Date,Double>();
        Map<Date,Decimal> tripTotalTimeMap = new Map<Date,Double>();
        for(Employee_Mileage__c objMileages : [SELECT id,EmployeeReimbursement__r.Name,Trip_Date__c,Day_Of_Week__c, 
                                                        Mileage__c, Driving_Time__c,Origin_Name__c,
                                                        ConvertedStartTime__c, ConvertedEndTime__c, 
                                                        Stay_Time__c, EmployeeReimbursement__r.Contact_Id__c,
                                                        EmployeeReimbursement__r.Contact_Id__r.Name,Total_Time__c
                                                    FROM Employee_Mileage__c 
                                                    WHERE EmployeeReimbursement__r.Contact_Id__c =: Id
                                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                                    AND Trip_Date__c <= : Date.valueOf(endDate)
                                                    ]){
            contactName = objMileages.EmployeeReimbursement__r.Contact_Id__r.Name;
            if(objMileages.Day_Of_Week__c != null ){
            tripdateDayMap.put(objMileages.Trip_Date__c, objMileages.Day_Of_Week__c);
            }
        }
        for(AggregateResult ar : [SELECT Trip_Date__c tdate, SUM(Mileage__c) rtotal
                                    FROM Employee_Mileage__c 
                                    WHERE EmployeeReimbursement__r.Contact_Id__c =: id 
                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                    AND Trip_Date__c <= : Date.valueOf(endDate) group by Trip_Date__c ]){

                                        tripdateMileageMap.put((Date)ar.get('tdate'),(Decimal)ar.get('rtotal'));
        }
        for(AggregateResult ar : [SELECT Trip_Date__c tdate, SUM(Driving_Time__c) rtotal
                                    FROM Employee_Mileage__c 
                                    WHERE EmployeeReimbursement__r.Contact_Id__c =: id 
                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                    AND Trip_Date__c <= : Date.valueOf(endDate) group by Trip_Date__c ]){

                                        tripdateDrivingTimeMap.put((Date)ar.get('tdate'),(Decimal)ar.get('rtotal'));
        }
        for(AggregateResult ar : [SELECT Trip_Date__c tdate, SUM(Stay_Time__c) rtotal
                                    FROM Employee_Mileage__c 
                                    WHERE EmployeeReimbursement__r.Contact_Id__c =: id 
                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                    AND Trip_Date__c <= : Date.valueOf(endDate) group by Trip_Date__c ]){

                                        tripStayTimeMap.put((Date)ar.get('tdate'),(Decimal)ar.get('rtotal'));
        }
        for(AggregateResult ar : [SELECT Trip_Date__c tdate, SUM(Total_Time__c) rtotal
                                    FROM Employee_Mileage__c 
                                    WHERE EmployeeReimbursement__r.Contact_Id__c =: id 
                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                    AND Trip_Date__c <= : Date.valueOf(endDate) group by Trip_Date__c ]){

                                        tripTotalTimeMap.put((Date)ar.get('tdate'),(Decimal)ar.get('rtotal'));
        }
        
        for(Date currentDate : tripdateDayMap.keySet())
        {
            List<String> dateSplitted = new List<String>();
            if(String.valueOf(currentDate) != null && String.valueOf(currentDate).contains('-')){
                dateSplitted = String.valueOf(currentDate).split('-');
            }
         
            if(totalMinute > 0 ){
                totalMinute = totalMinute + Integer.valueOf(tripdateDrivingTimeMap.get(currentDate));
            } else {
                totalMinute = Integer.valueOf(tripdateDrivingTimeMap.get(currentDate));
            }
            
            if(totalStay > 0 && tripStayTimeMap.containsKey(currentDate)){
                totalStay = totalStay + Integer.valueOf(tripStayTimeMap.get(currentDate));
            } else {
                totalStay = Integer.valueOf(tripStayTimeMap.get(currentDate));
            }

            if(totalTimes > 0 && tripTotalTimeMap.containsKey(currentDate)){
                totalTimes = totalTimes + Integer.valueOf(tripTotalTimeMap.get(currentDate));
            } else {
                totalTimes = Integer.valueOf(tripTotalTimeMap.get(currentDate));
            }

            mileageWrapper objMileageWrap = new mileageWrapper();
            if(!dateSplitted.isEmpty()){
                objMileageWrap.tripDate = dateSplitted[1]+'/'+dateSplitted[2]+'/'+dateSplitted[0].substring(2,4);
            }
            objMileageWrap.tripDay = tripdateDayMap.get(currentDate);
            objMileageWrap.mileage = tripdateMileageMap.get(currentDate);
            objMileageWrap.totaldrivingTime = Utils.ConvertMinuteToHours(Integer.valueOf(tripdateDrivingTimeMap.get(currentDate)));
            objMileageWrap.totalStayTime = Utils.ConvertMinuteToHours(Integer.valueOf(tripStayTimeMap.get(currentDate)));
            objMileageWrap.totalTime = Utils.ConvertMinuteToHours(Integer.valueOf(tripTotalTimeMap.get(currentDate)));
            if(totalMileges > 0 ){
                totalMileges = totalMileges + objMileageWrap.mileage;
            } else {
                totalMileges = objMileageWrap.mileage;
            }
            
            mileageWrapperList.add(objMileageWrap);
        }
        System.debug('mileageWrapperList'+mileageWrapperList);
        totalTimeForMonth = Utils.ConvertMinuteToHours(totalTimes); 
        totalDriveTime = Utils.ConvertMinuteToHours(totalMinute);
        totalStayTimeForMonth = Utils.ConvertMinuteToHours(totalStay);
    }

    public class mileageWrapper{
        public string tripDate { get; set; }
        public string tripDay { get; set; }
        public decimal mileage { get; set; }
        public String totaldrivingTime { get; set; }
        public String totalStayTime { get; set; }
        public String totalTime { get; set; }
        public mileageWrapper(){
        }
    }
}