force-app/main/default/objects/Contact/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver - Part Time</fullName>
            </value>
            <value>
                <fullName>Driver - Full Time</fullName>
            </value>
            <value>
                <fullName>Driver - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Employee_Netchex_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Netchex_Id__c</fullName>
    <label>Employee Netchex Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <label>Trip Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Drive_Stay_Time__c.field-meta.xml
<CustomField>
    <fullName>Drive_Stay_Time__c</fullName>
    <formula>Driving_Time__c + Stay_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drive Stay Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TimeSheetReportController.cls
/*
 * @Author:  GetonCRM Solutions LLP
 * @Description:  Apex class use to download a excel file for Timesheet report same as netchex time and attedance report.
 * ------------------------------------------------------------------------------------------------------------------------
 * @Modification Logs
 * ------------------------------------------------------------------------------------------------------------------------
 * @version 1.1   - @Author:  Sanket Goswami - 2 Sept 2020
 */
public with sharing class TimeSheetReportController {
    public List<ReibursementWrapper> timeWrapperList{get;set;}
    public String xlsHeader{
        get{
            String strHeader = '';
            strHeader += '<?xml version="1.0" encoding="UTF-8"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }
    public TimeSheetReportController() {
        TimeSheet();
    }
    public void TimeSheet(){
        //String Id = ApexPages.currentPage().getParameters().get('id');
        String startDate = ApexPages.currentPage().getParameters().get('startDate');
        String endDate = ApexPages.currentPage().getParameters().get('endDate');
        timeWrapperList = new List<ReibursementWrapper>();
        Map<Id, Decimal> reimbTotalTimeMap = new Map<Id, Decimal>();
        for(AggregateResult ar : [SELECT EmployeeReimbursement__r.Contact_Id__c rid, SUM(Drive_Stay_Time__c) rtotal 
                                FROM Employee_Mileage__c 
                                WHERE (EmployeeReimbursement__r.Contact_Id__r.Driver_Type__c = 'Driver - Full Time' 
                                        OR EmployeeReimbursement__r.Contact_Id__r.Driver_Type__c = 'Driver - Part Time') 
                                        AND EmployeeReimbursement__r.Contact_Id__r.AccountId =: System.Label.ERMI_Account
                                        AND Trip_Date__c >= : Date.valueOf(startDate)
                                        AND Trip_Date__c <= : Date.valueOf(endDate) group by EmployeeReimbursement__r.Contact_Id__c]) {
                                reimbTotalTimeMap.put((Id)ar.get('rid'), (Decimal) ar.get('rtotal')); 
        }
        for(Contact currentContact : [SELECT id,Employee_Netchex_Id__c,Code__c FROM Contact WHERE (Driver_Type__c = 'Driver - Full Time' OR Driver_Type__c = 'Driver - Part Time')AND Employee_Netchex_Id__c != null AND AccountId =: System.Label.ERMI_Account]){
            ReibursementWrapper objWrapper = new ReibursementWrapper();
            objWrapper.CompanyCode = 'LIL';
            objWrapper.EntryDate = endDate;
            objWrapper.EmployeeId = currentContact.Employee_Netchex_Id__c;
            objWrapper.GrossToNetCode = '1';
            objWrapper.TypeCode = 'R';
            if(reimbTotalTimeMap.get(currentContact.Id) == null ){
                objWrapper.HoursOrAmount = 0;
            }
            else{
                objWrapper.HoursOrAmount = (reimbTotalTimeMap.get(currentContact.Id)).divide(60, 2);
            }
            timeWrapperList.add(objWrapper);
        }
    }

    public class ReibursementWrapper{
        public string CompanyCode { get; set; }
        public string EntryDate { get; set; }
        public string EmployeeId { get; set; }
        public string GrossToNetCode { get; set; }
        public string TypeCode { get; set; }
        public double HoursOrAmount { get; set; }
        public ReibursementWrapper(){
        }
    }
}