force-app/main/default/objects/Contact/fields/Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Deactivated_Date__c</fullName>
    <inlineHelpText>Date employee is deactivated. They will receive the fixed and last months variable.</inlineHelpText>
    <label>Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/isCommunityUser__c.field-meta.xml
<CustomField>
    <fullName>isCommunityUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCommunityUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Role__c</field>
            <operation>equals</operation>
            <value>Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Mileage_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Mileage_Limit__c</fullName>
    <inlineHelpText>Manager selects how many miles can be driven for auto approval.</inlineHelpText>
    <label>Monthly Mileage Limit</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <description>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</description>
    <inlineHelpText>Format should be like this: Year Vehicle Name 
Ex. 2019 Ford Sedan</inlineHelpText>
    <label>Standard Vehicle Make Model and Year</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/Custom_Report__c.object-meta.xml
<CustomObject>
    <label>Custom Report</label>
    <nameField>
        <label>Custom Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Report__c/fields/Numeric_Fields__c.field-meta.xml
<CustomField>
    <fullName>Numeric_Fields__c</fullName>
    <label>Numeric Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Report_Category__c.field-meta.xml
<CustomField>
    <fullName>Report_Category__c</fullName>
    <label>Report Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>My Custom Reports</fullName>
            </value>
            <value>
                <fullName>Reconciliation Reports</fullName>
            </value>
            <value>
                <fullName>Reimbursement Reports</fullName>
            </value>
            <value>
                <fullName>Tax Liability Reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Report_For__c.field-meta.xml
<CustomField>
    <fullName>Report_For__c</fullName>
    <label>Report For</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Report_Header__c.field-meta.xml
<CustomField>
    <fullName>Report_Header__c</fullName>
    <description>Report Header</description>
    <inlineHelpText>Report Header with comma sepration</inlineHelpText>
    <label>Report Header</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Report_Soql__c.field-meta.xml
<CustomField>
    <fullName>Report_Soql__c</fullName>
    <label>Report Soql</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contact Created Between 2 Dates</fullName>
            </value>
            <value>
                <fullName>Contact Activation Between 2 Dates</fullName>
            </value>
            <value>
                <fullName>Contact Deactivation Between 2 Dates</fullName>
            </value>
            <value>
                <fullName>Reimbursements Created Between 2 Dates</fullName>
            </value>
            <value>
                <fullName>Reimbursements Between 2 Deactivation Dates</fullName>
            </value>
            <value>
                <fullName>Reimbursements Between 2 Dates For Month Range</fullName>
            </value>
            <value>
                <fullName>Mileages Between 2 Trip Dates</fullName>
            </value>
            <value>
                <fullName>Mileages Created Between 2 Dates</fullName>
            </value>
            <value>
                <fullName>Mileages Between 2 Deactivation Dates</fullName>
            </value>
            <value>
                <fullName>Mileages Between 2 Dates for Month Range</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Without Date Range</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Sort_By__c.field-meta.xml
<CustomField>
    <fullName>Sort_By__c</fullName>
    <label>Sort By</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Use_Manager_List__c.field-meta.xml
<CustomField>
    <fullName>Use_Manager_List__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Manager List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id_Deactivated_Date__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id_Deactivated_Date__c</fullName>
    <formula>Contact_Id__r.Deactivated_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Id Deactivated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id_Employee_ID__c</fullName>
    <formula>Contact_Id__r.Employee_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Id Employee ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id_External_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id_External_Email__c</fullName>
    <formula>Contact_Id__r.External_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Id External Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id_Name__c</fullName>
    <formula>Contact_Id__r.FirstName+&apos; &apos;+Contact_Id__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Id Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fuel_Price__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Price__c</fullName>
    <label>Fuel Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Monthly_Approved_Variable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Approved_Variable_Amount__c</fullName>
    <formula>Total_Approved__c * Total_Variable_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Approved Variable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>VALUE(RIGHT(Month__c,Find(&quot;-&quot;, Month__c)+1))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Report_Accessibility__c/Report_Accessibility__c.object-meta.xml
<CustomObject>
    <label>Report Accessibility</label>
    <nameField>
        <label>Report Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Accessibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Accessibility__c/fields/Custom_Report__c.field-meta.xml
<CustomField>
    <fullName>Custom_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Report</label>
    <referenceTo>Custom_Report__c</referenceTo>
    <relationshipLabel>Report Accessibilities</relationshipLabel>
    <relationshipName>Report_Accessibilities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Accessibility__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Report_Accessibilities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SendEmail__c/SendEmail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Send Email</label>
</CustomObject>

force-app/main/default/objects/SendEmail__c/fields/Send_email_from_code__c.field-meta.xml
<CustomField>
    <fullName>Send_email_from_code__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send email from code</description>
    <label>Send email from code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerConfig__c/TriggerConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TriggerConfig:- MappingGasPriceTrigger</description>
    <label>TriggerConfig</label>
</CustomObject>

force-app/main/default/objects/TriggerConfig__c/fields/ContactTriggersendEmailForNewContact__c.field-meta.xml
<CustomField>
    <fullName>ContactTriggersendEmailForNewContact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Use in contact trigger helper class for sendEmailForNewContact method.</description>
    <label>ContactTriggersendEmailForNewContact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/Vehicle_URL_Mapping__c.object-meta.xml
<CustomObject>
    <label>Vehicle URL Mapping</label>
    <nameField>
        <label>Vehicle URL Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle URL Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_URL_Mapping__c/fields/vehicle__c.field-meta.xml
<CustomField>
    <fullName>vehicle__c</fullName>
    <label>vehicle</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ReportListController_Test.cls
@isTest
public class ReportListController_Test {
    public static testmethod void ReportListControllerTestMethod() {
        Vehicle_URL_Mapping__c veh = new Vehicle_URL_Mapping__c();
        veh.URL__c = 'https://cdn2.hubspot.net/hubfs/2511299/iStock-494093356.jpg';
        veh.vehicle__c =  'Full-Size Sedan';
        veh.Year__c = '2019';
        insert veh;
        //sendEmail custom setting
        SendEmail__c customSetting2 =  new SendEmail__c();
        customSetting2.Name = 'Send Email For Compliance';
        customSetting2.Send_email_from_code__c= true;
        insert customSetting2;

        TriggerConfig__c customEmailSetting =  new TriggerConfig__c();
        customEmailSetting.Name = 'Defaulttrigger';
        customEmailSetting.ContactTriggersendEmailForNewContact__c = true;
        insert customEmailSetting;

        //Account
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        //Contact driver List
        List<Contact> driList = new List<Contact>();
        //Contact Admin
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact Admin';
        con.AccountId = acc.Id;
        con.MailingStreet = 'Test Street';
        con.MailingCity = 'Test City';
        con.MailingState = 'ON';
        con.MailingPostalCode = '123';
        con.MailingCountry = 'CA';
        con.Phone = '1232434445';
        con.External_Email__c = 'minkesh.pateladmin01@gmail.com';
        con.Deactivated_Date__c = null;
        con.IsCommunityUser__c = true;
        con.Role__c = 'Admin';
        con.Monthly_Mileage_Limit__c = 200;
        con.Vehicle_Type__c = '2019 Full-Size Sedan';
        insert con;
        //Contact Manager
        Contact co = new Contact();
        co.FirstName = 'Test';
        co.LastName = 'Contact Manager';
        co.AccountId = acc.Id;
        co.MailingStreet = 'Test Street';
        co.MailingCity = 'Test City';
        co.MailingState = 'ON';
        co.MailingPostalCode = '123';
        co.MailingCountry = 'CA';
        co.Phone = '1232434445';
        co.External_Email__c = 'minkesh.patelmanager01@gmail.com';
        co.Deactivated_Date__c = null;
        co.IsCommunityUser__c = true;
        co.Role__c = 'Manager';
        co.Monthly_Mileage_Limit__c = 210;
        co.Manager__c = con.Id;
        co.Vehicle_Type__c = '2019 Full-Size Sedan';
        insert co;
        //Contact Driver
        Contact c;
        for(Integer i = 0; i<5; i++) {
            c = new Contact();
            c.FirstName = 'Test';
            c.LastName = 'Contact Manager'+i;
            c.AccountId = acc.Id;
            c.MailingStreet = 'Test Street';
            c.MailingCity = 'Test City';
            c.MailingState = 'ON';
            c.MailingPostalCode = '123';
            c.MailingCountry = 'CA';
            c.Phone = '1232434445';
            c.External_Email__c = 'minkesh.pateldriver01'+i+'@gmail.com';
            c.Deactivated_Date__c = null;
            c.IsCommunityUser__c = true;
            c.Role__c = 'Driver';
            c.Monthly_Mileage_Limit__c = 210;
            c.Manager__c = co.Id;
            c.Vehicle_Type__c = '2019 Full-Size Sedan';
            driList.add(c);
        }
        insert driList;

        Employee_Reimbursement__c er = new Employee_Reimbursement__c();
        er.Contact_Id__c = driList[0].Id;
        er.Name = 'Reimbersment Test';
        er.Month__c = '06-2020';
        er.Status__c = 'Pending';
        er.Fuel_Price__c = 10.00;
        insert er;

        //User
        Profile p = [SELECT Id FROM Profile WHERE Name='Customer Community Login User - Manager'];
      

        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8',FirstName='Test', LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US',ProfileId=p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='Testingapexclass@gmail.com',Contactid=driList[0].id);
    
        insert u;
        //Custom report

        Custom_Report__c currentReport = new Custom_Report__c();
        currentReport.Name = 'Variable Reimbursement Report';
        currentReport.Sort_By__c = 'asc';
        currentReport.Report_For__c = 'Frank Saverino Accessibility';
        currentReport.Report_Category__c = 'Reimbursement Reports  ';
        currentReport.Report_Type__c = 'Reimbursements Between 2 Dates For Month Range';
        currentReport.Use_Manager_List__c = true;
        currentReport.Report_Header__c = 'Month,Employee ID,Name,E-mail,Monthly Approved Variable Amount';
        currentReport.Report_Soql__c = 'select Month__c,Contact_Id_Employee_ID__c,Contact_Id_Name__c,Contact_Id_External_Email__c,Monthly_Approved_Variable_Amount__c from Employee_Reimbursement__c where Contact_Id_Deactivated_Date__c =null';
        currentReport.Numeric_Fields__c = 'Monthly_Approved_Variable_Amount__c';
        currentReport.Date_Time_Fields__c = 'Contact_Id_Name__c';
        currentReport.Date_Fields__c = 'Contact_Id_External_Email__c';
        insert currentReport ; 

        // Custom_Report__c rep = new Custom_Report__c();
        // rep.Name = 'Test Productivity Report';
        // rep.Report_Category__c = 'My Custom Reports';
        // rep.Report_For__c = 'tesst';
        // rep.Report_Soql__c = 'SELECT id,Name,email from contact where Account.name=\'Test Account\'';
        // rep.Report_Type__c = 'test';
        // rep.Sort_By__c = 'asc';
        // rep.Sort_From__c = '2';
        // insert rep;

        
        Report_Accessibility__c repAcc = new Report_Accessibility__c();
        repAcc.Custom_Report__c = currentReport.Id;
        repAcc.User__c = u.Id;
        insert repAcc;

        Test.startTest();
        Test.setCurrentPage(Page.reportlist);
        String accId = ApexPages.currentPage().getParameters().put('accid',acc.Id);
        String conid = ApexPages.currentPage().getParameters().put('id',driList[0].Id);
        ReportListController mddc = new ReportListController();
        ReportListController.getAccountid();
        ReportListController.getContactid();
        ReportListController.getRedirected();
        ReportListController.getAllReports();
        ReportListController.getRole();
        ReportListController.reimbursementListModal(er.Id);
        ReportListController.contactListModal(acc.Id);
        String startDate = '2020-01-01';
        String endDate = '2020-03-22';
        ReportListController.postTimeSheetImportAPI(startDate,endDate,con.id);
        ReportListController.postVariablePaymentAPI(startDate,con.id);
        ReportListController.postFixedAmountAPI(startDate,con.id);
        ReportListController.postHalfFPFullDriverAPI(startDate,endDate,con.id);
        ReportListController.CheckStatus(1234567654,'NetchexDeleteCallout');
        Test.stopTest();
    }
}