force-app/main/default/objects/Contact/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver - Part Time</fullName>
            </value>
            <value>
                <fullName>Driver - Full Time</fullName>
            </value>
            <value>
                <fullName>Driver - Salary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/isCommunityUser__c.field-meta.xml
<CustomField>
    <fullName>isCommunityUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isCommunityUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Driver/Manager</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Driver/Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Report__c/Custom_Report__c.object-meta.xml
<CustomObject>
    <label>Custom Report</label>
    <nameField>
        <label>Custom Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Report__c/fields/Report_Category__c.field-meta.xml
<CustomField>
    <fullName>Report_Category__c</fullName>
    <label>Report Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>My Custom Reports</fullName>
            </value>
            <value>
                <fullName>Reconciliation Reports</fullName>
            </value>
            <value>
                <fullName>Reimbursement Reports</fullName>
            </value>
            <value>
                <fullName>Tax Liability Reports</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Report__c/fields/Show_Lock_Date__c.field-meta.xml
<CustomField>
    <fullName>Show_Lock_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Lock Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Mileage_Lock_Date__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Lock_Date__c</fullName>
    <label>Mileage Lock Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Report_Accessibility__c/Report_Accessibility__c.object-meta.xml
<CustomObject>
    <label>Report Accessibility</label>
    <nameField>
        <label>Report Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Accessibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Report_Accessibility__c/fields/Custom_Report__c.field-meta.xml
<CustomField>
    <fullName>Custom_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Custom Report</label>
    <referenceTo>Custom_Report__c</referenceTo>
    <relationshipLabel>Report Accessibilities</relationshipLabel>
    <relationshipName>Report_Accessibilities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Report_Accessibility__c/fields/Mileage_Lock_Date__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Lock_Date__c</fullName>
    <label>Mileage Lock Date</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Report_Accessibility__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Report_Accessibilities_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/Tripslog__c.object-meta.xml
<CustomObject>
    <label>Tripslog</label>
    <nameField>
        <displayFormat>Tripno-{0000000}</displayFormat>
        <label>Triplog No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tripslogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tripslog__c/fields/Employee_Reimbursement__c.field-meta.xml
<CustomField>
    <fullName>Employee_Reimbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Employee Reimbursement</description>
    <inlineHelpText>Employee Reimbursement</inlineHelpText>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Tripslogs</relationshipLabel>
    <relationshipName>Tripslogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Log_Time__c.field-meta.xml
<CustomField>
    <fullName>Log_Time__c</fullName>
    <label>Log Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Response</description>
    <inlineHelpText>Response</inlineHelpText>
    <label>Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tripslog__c/fields/Response_Data__c.field-meta.xml
<CustomField>
    <fullName>Response_Data__c</fullName>
    <label>Response Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ReportListController.cls
/**
@author Natavar Ghodasara
@date 26th Feb 2019
@description DriverDashboardController is used to show/edit Employee details.
*/
public with sharing class ReportListController 
{
    public List<reimbursementWrapper> reimWrapperList {get; set;}
    public string reimburName {get; set;}
    public ReportListController() 
    {  
        reimWrapperList = new List<reimbursementWrapper>();
        if(System.Label.ERMI_Account == getAccountid()){
            for(Contact currentContact : [SELECT id,Name 
                                            FROM Contact 
                                            WHERE isCommunityUser__c = true 
                                                AND AccountId =: System.Label.ERMI_Account 
                                                AND (Driver_Type__c = 'Driver - Part Time' 
                                                OR Driver_Type__c = 'Driver - Full Time')
                                                Order By FirstName ]) {
                reimbursementWrapper objWrapper = new reimbursementWrapper();
                objWrapper.reimbId = currentContact.id;
                objWrapper.name = currentContact.Name;
                reimWrapperList.add(objWrapper);
            }
        } else if(System.label.FramptonConstruction == getAccountid()){
            for(Contact currentContact : [SELECT id,Name 
                                            FROM Contact 
                                            WHERE isCommunityUser__c = true 
                                                AND AccountId =: System.Label.FramptonConstruction 
                                                Order By FirstName ]) {
                reimbursementWrapper objWrapper = new reimbursementWrapper();
                objWrapper.reimbId = currentContact.id;
                objWrapper.name = currentContact.Name;
                reimWrapperList.add(objWrapper);
            }
        }
        reimburName = JSON.serialize(reimWrapperList);
    }
    public static String getAccountid() {
        if (ApexPages.currentPage().getParameters().containsKey('accid')) {
            return ApexPages.currentPage().getParameters().get('accid');
        } else {
            return '';
        }
    }
    public static String getContactid() {
        if (ApexPages.currentPage().getParameters().containsKey('id')) {
            return ApexPages.currentPage().getParameters().get('id');
        } else {
            return '';
        }
    }
    public static PageReference getRedirected() {

        if (getContactid() != '' && getAccountid() != '') {
            return null;
        } else {
// redirect to error page
            return null;
        }

    }

    public static string getRole() {

        List<Contact> conRole = [SELECT Id, Role__c FROM Contact WHERE id =: getContactid()]; 
        string role = conRole[0].Role__c;
        return role;
    }

    public static string EmailAddress(String adminId) {
        List<Contact> conEmail = [SELECT Id, External_Email__c FROM Contact WHERE id =: adminId]; 
        string email = conEmail[0].External_Email__c;
        return email;
    }

    public static string AdminName(String adminId) {
        List<Contact> conName = [SELECT Id,FirstName FROM Contact WHERE id =: adminId]; 
        string name = conName[0].FirstName;
        return name;
    }

    public static string getAllReports()
    {   

        Map<String,List<Report_Accessibility__c>> obj_map_report_Accessibility = new Map<String,List<Report_Accessibility__c>>();
        for(Report_Accessibility__c obj_currentreportaccesibilty:[SELECT Custom_Report__r.ownerid,Custom_Report__r.Name,Custom_Report__c,Custom_Report__r.Report_Category__c,Custom_Report__r.Show_Lock_Date__c,Mileage_Lock_Date__c FROM Report_Accessibility__c WHERE user__r.contactid=:getContactid() Order By Custom_Report__r.Report_Category__c])
        {
            if(obj_map_report_Accessibility.containsKey(obj_currentreportaccesibilty.Custom_Report__r.Report_Category__c))
            {
                
                obj_map_report_Accessibility.get(obj_currentreportaccesibilty.Custom_Report__r.Report_Category__c).add(obj_currentreportaccesibilty);   
            }
            else
            {
                List<Report_Accessibility__c> obj_Report_Accessibility_list = new List<Report_Accessibility__c>();
                obj_Report_Accessibility_list.add(obj_currentreportaccesibilty);
                obj_map_report_Accessibility.put(obj_currentreportaccesibilty.Custom_Report__r.Report_Category__c,obj_Report_Accessibility_list);   
            }
            
        }
        List<CategoryWiseReportList> obj_CategoryWiseReportList = new List<CategoryWiseReportList>();
        for(String s:obj_map_report_Accessibility.keySet())
        {
            CategoryWiseReportList obj = new CategoryWiseReportList();
            obj.categoryName = s;
            System.debug('obj.categoryName'+obj.categoryName);
            List<CategoryWiseReportList.Reports> reportsList = new List<CategoryWiseReportList.Reports>();
            for(Report_Accessibility__c r : obj_map_report_Accessibility.get(s))
            {
                CategoryWiseReportList.Reports obj_report = new CategoryWiseReportList.Reports();
                obj_report.reportId = r.Custom_Report__c;
                obj_report.reportName = r.Custom_Report__r.Name;
                System.debug('r.Custom_Report__r.Name;'+r.Custom_Report__r.Show_Lock_Date__c);  
                obj_report.lockDate = r.Custom_Report__r.Show_Lock_Date__c; 
                obj_report.mileageLockDate = String.valueOf(r.Mileage_Lock_Date__c);
                reportsList.add(obj_report);
            }
            obj.currentReports = reportsList;
            obj_CategoryWiseReportList.add(obj);
        }

        return JSON.serialize(obj_CategoryWiseReportList);      
    }

    //AI-000426
    @RemoteAction
    public static void updateLockDate(String accountId, String lockDate,String contactId){
        System.debug('accountId'+accountId+''+'lockDate'+lockDate+ 'contactId'+contactId);
        WrapperUtils.updateLockDate(accountId,lockDate,contactId);
    }

    //AI-000150
    @RemoteAction
    public static List<Contact> contactListModal(String accId){
        List<Contact> contactList = new List<Contact>();
        for(contact currentContact:[SELECT id,FirstName,LastName FROM Contact WHERE (Role__c = 'Driver' OR Role__c =: StaticValues.roleAdminDriver OR Role__c = 'Manager/Driver') and Account.id =: accId ORDER BY FirstName])
        {
            contactList.add(currentContact);
        }
        System.debug('-----------'+contactList);
        return contactList; 
    }

    @RemoteAction
    public static List<Employee_Reimbursement__c> reimbursementListModal(String reimbId){
        List<Employee_Reimbursement__c> reimbursementList = new List<Employee_Reimbursement__c>();
        for(Employee_Reimbursement__c currentReimbursement : [SELECT id,Name FROM Employee_Reimbursement__c WHERE Contact_Id__c =: reimbId  order by CreatedDate desc])
        {
            reimbursementList.add(currentReimbursement);
        }
        return reimbursementList;   
    }
    
    @RemoteAction
    public static DateTime postTimeSheetImportAPI(String startDate, String endDate,String adminId){
        DateTime runTime = System.Now();
        String AdminEmail = EmailAddress(adminId);
        String name = AdminName(adminId);
        TimeSheetImportNetchexBatch tripBtc = new TimeSheetImportNetchexBatch(startDate, endDate, runTime, AdminEmail, name);
		Database.executeBatch(tripBtc,200);
		return runTime;
    }

    @RemoteAction
    public static DateTime postVariablePaymentAPI(String startDate,String adminId){
        DateTime runTime = System.Now();
        String AdminEmail = EmailAddress(adminId);
        String name = AdminName(adminId);
        NetchexVariablePaymentBatch tripBtc = new NetchexVariablePaymentBatch(runTime,startDate,AdminEmail,name);
		Database.executeBatch(tripBtc,200);
		return runTime;
    }

    @RemoteAction
    public static DateTime postFixedAmountAPI(String startDate,String adminId){
        DateTime runTime = System.Now();
        String AdminEmail = EmailAddress(adminId);
        String name = AdminName(adminId);
        NetchexSalaryPartFixAmountBatch tripBtc = new NetchexSalaryPartFixAmountBatch(runTime,startDate,AdminEmail,name);
        Database.executeBatch(tripBtc,200);
        return runTime;
    }
    
    @RemoteAction
    public static PollarResponse CheckStatus(Long longtime, String batchName){
        DateTime runTime = DateTime.newInstance(longtime);
        List<Tripslog__c> logList = [SELECT Id, Response_Data__c  FROM Tripslog__c WHERE Log_Time__c =: runTime AND Response__c =: batchName];
        PollarResponse res = new PollarResponse();
        res.enablePollar = true;
        if(!logList.isEmpty()) {
            res.enablePollar = false; 
            res.message = logList.get(0).Response_Data__c;
        }
        return res;
    }

    @RemoteAction
    public static DateTime postHalfFPFullDriverAPI(String startDate, String endDate,String adminId){
        DateTime runTime = System.Now();
        String AdminEmail = EmailAddress(adminId);
        String name = AdminName(adminId);
        NetchexFulltimeHalfFPBatch tripBtc = new NetchexFulltimeHalfFPBatch(runTime,startDate,endDate,AdminEmail,name);
		Database.executeBatch(tripBtc,200);
		return runTime;
    }

    @RemoteAction
    public static DateTime DeleteNetchexCallout(String startDate,String endDate){
		DateTime runTime = System.Now();
		NetchexDeleteCallout.DeletedataFromNetchex(startDate,endDate,runTime);
		return runTime;
    }
    public class reimbursementWrapper{
        public Id reimbId { get; set; }
        public string name { get; set; }
    }
    
    public class PollarResponse {
        public Boolean enablePollar;
        public String Message;
    }
}