force-app/main/default/objects/Contact/fields/External_Email__c.field-meta.xml
<CustomField>
    <fullName>External_Email__c</fullName>
    <externalId>true</externalId>
    <label>External Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <label>Trip Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/EmployeeReimbursement__c.field-meta.xml
<CustomField>
    <fullName>EmployeeReimbursement__c</fullName>
    <label>Employee Reimbursement</label>
    <referenceTo>Employee_Reimbursement__c</referenceTo>
    <relationshipLabel>Employees Mileage</relationshipLabel>
    <relationshipName>Employees_Mileage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Status__c.field-meta.xml
<CustomField>
    <fullName>Trip_Status__c</fullName>
    <label>Trip Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Approved Yet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Approved_Date__c.field-meta.xml
<CustomField>
    <fullName>Approved_Date__c</fullName>
    <label>Approved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Reimbursements</relationshipLabel>
    <relationshipName>Employee_Reimbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/fields/Total_Variable_Rate__c.field-meta.xml
<CustomField>
    <fullName>Total_Variable_Rate__c</fullName>
    <formula>Fuel_Variable_Rate__c  +  Maintenance_and_Tires__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Variable Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmployeeMileagesforAISaccController.cls
/*
 * @Author:  GetonCRM Solutions LLP
 * @Description:  Apex class use to download a excel file for total reimbursment for AIS account.
 * ------------------------------------------------------------------------------------------------------------------------
 * @Modification Logs
 * Page Name :- MileagesforAISAccountReport
 * ------------------------------------------------------------------------------------------------------------------------
 * @version 1.1   - @Author:  Sanket Goswami - 22 Feb 2021
 */
public with sharing class EmployeeMileagesforAISaccController {
    public List<milWrapper> milWrapList {get; set; }
    public String xlsHeader{
        get{
            String strHeader = '';
            strHeader += '<?xml version="1.0" encoding="UTF-8"?>';
            strHeader += '<?mso-application progid="Excel.Sheet"?>';
            return strHeader;
        }
    }

    public EmployeeMileagesforAISaccController() {
        getEmployeeMileages();
    }
    
    // This method is used to get the mileages and do sum of that trips and calculate total reimbursement.
    public void getEmployeeMileages() {
        //String startDate = '2021-01-01';
        //String endDate = '2021-01-31';
        String startDate = ApexPages.currentPage().getParameters().get('startDate');
        String endDate = ApexPages.currentPage().getParameters().get('endDate');
        milWrapList = new List<milWrapper>();
        Map<Id, Decimal> mileageMap = new Map<Id, Decimal>();
        Map<Id, Decimal> fixedAmountMap = new Map<Id, Decimal>();
        Map<Id, Decimal> totalVariAmountMap = new Map<Id, Decimal>();
        List<String> lastPaydateSplitted = new List<String>();
        system.debug('startDate=='+startDate);
        if((String.valueOf(startDate).contains('-'))) {
                        lastPaydateSplitted = String.valueOf(startDate).split('-');                
        }
        String reimMonth = lastPaydateSplitted[1]+'-'+lastPaydateSplitted[0];
        for(AggregateResult ar : [SELECT EmployeeReimbursement__r.Contact_Id__c rid, SUM(Mileage__c) rtotal
                                FROM Employee_Mileage__c 
                                WHERE   EmployeeReimbursement__r.Contact_Id__r.Account.Name = 'Advanced Inventory Solutions'
                                        AND Trip_Date__c >= : Date.valueOf(startDate)
                                        AND Trip_Date__c <= : Date.valueOf(endDate)
                                        AND Trip_Status__c = 'Approved' 
                                  AND Approved_Date__c != null group by EmployeeReimbursement__r.Contact_Id__c]) {
            mileageMap.put((Id)ar.get('rid'), (Decimal) ar.get('rtotal')); 
                                   
        }

        for(Employee_Mileage__c objMil : [SELECT EmployeeReimbursement__r.Contact_Id__c,
                                                    EmployeeReimbursement__r.Fixed_Amount__c, 
                                                    EmployeeReimbursement__r.Total_Variable_Rate__c
                                            FROM Employee_Mileage__c 
                                            WHERE   EmployeeReimbursement__r.Contact_Id__r.Account.Name = 'Advanced Inventory Solutions'
                                                    AND Trip_Date__c >= : Date.valueOf(startDate)
                                                    AND Trip_Date__c <= : Date.valueOf(endDate)
                                                    AND Trip_Status__c = 'Approved' 
                                          AND Approved_Date__c != null]) {
            if(objMil.EmployeeReimbursement__r.Fixed_Amount__c == null){
                objMil.EmployeeReimbursement__r.Fixed_Amount__c = 0;
            } 
            fixedAmountMap.put(objMil.EmployeeReimbursement__r.Contact_Id__c,objMil.EmployeeReimbursement__r.Fixed_Amount__c); 
            totalVariAmountMap.put(objMil.EmployeeReimbursement__r.Contact_Id__c,objMil.EmployeeReimbursement__r.Total_Variable_Rate__c);                                         
        }
        for(Contact currentContact : [SELECT id,Name,External_Email__c FROM Contact WHERE Account.Name = 'Advanced Inventory Solutions']){
            Decimal monthlyVariableAmount;
            if(totalVariAmountMap.containsKey(currentContact.Id) && mileageMap.containsKey(currentContact.Id)){
                monthlyVariableAmount = totalVariAmountMap.get(currentContact.Id) * mileageMap.get(currentContact.Id);
            } else {
                monthlyVariableAmount = 0;
            }
            
            milWrapper objWrap = new milWrapper();
            objWrap.name = currentContact.Name;
            objWrap.email = currentContact.External_Email__c;
            if(fixedAmountMap.containsKey(currentContact.Id)){
                objWrap.TotalReim = (monthlyVariableAmount + fixedAmountMap.get(currentContact.Id)).setScale(2);
            } else {
                objWrap.TotalReim = (monthlyVariableAmount + 0).setScale(2);
            }
            milWrapList.add(objWrap);
        }
     
    }

    public class milWrapper {
        public string name { get; set; }
        public string email { get; set; }
        //public string tripdate { get; set; }
        public decimal TotalReim { get; set; }
        public milWrapper(){}
    }
}