force-app/main/default/objects/Contact/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <label>Trip Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/Employee_Mileage__c.object-meta.xml
<CustomObject>
    <label>Employee Mileage</label>
    <nameField>
        <label>Employee Mileage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees Mileage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Date__c.field-meta.xml
<CustomField>
    <fullName>Trip_Date__c</fullName>
    <description>Date and Time Trip was Logged</description>
    <inlineHelpText>Date and Time Trip was Logged</inlineHelpText>
    <label>Trip Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Mileage__c/fields/Trip_Id__c.field-meta.xml
<CustomField>
    <fullName>Trip_Id__c</fullName>
    <externalId>true</externalId>
    <label>Trip Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee_Reimbursement__c/Employee_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Employee Reimbursement</label>
    <nameField>
        <label>Employee ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Reimbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SendEmailonDeactivation__c/SendEmailonDeactivation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Send Email on Deactivation</label>
</CustomObject>

force-app/main/default/objects/SendEmailonDeactivation__c/fields/BCCEmailaddresses__c.field-meta.xml
<CustomField>
    <fullName>BCCEmailaddresses__c</fullName>
    <label>BCCEmailaddresses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SendEmailonDeactivation__c/fields/Send_to_Admin__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailonDeactivation__c/fields/Send_to_Manager__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailonDeactivation__c/fields/Send_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_to_me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SendEmailToMe__c/SendEmailToMe__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SendEmailToMe</label>
</CustomObject>

force-app/main/default/objects/SendEmailToMe__c/fields/Send_email_to_me__c.field-meta.xml
<CustomField>
    <fullName>Send_email_to_me__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send email to me</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChangeTripStatusinTripLogTest.cls
@isTest
public with sharing class ChangeTripStatusinTripLogTest {
   
    public static testmethod void method1() {

        SendEmailToMe__c sendemailme = new SendEmailToMe__c();
        sendemailme.name = 'ChangeTripStatusinTripLog';
        sendemailme.Send_email_to_me__c = true;
        insert sendemailme;

        RecordUtilityClass.createRecordsAdminDashboardController();
            Test.setMock(HttpCalloutMock.class, new ChangeTripStatusinTripLogTestMock());
            Account currentAccount = RecordUtilityClass.getAccount(); // retriving the Accounts EmployeeMileagesForCalculation
            Contact currentAdmin = RecordUtilityClass.getAdminContact(); // Retriving the Admin with limit 1
            Contact selectedDriver = RecordUtilityClass.getDriverContact();
            List<String> approvedIdList = new List<String>();
            List<String> rejectedIdList = new List<String>();   
            List<Employee_Reimbursement__c> empReimbursementList = RecordUtilityClass.getEmployee_Reimbursement(currentAccount.id);
            List<EmployeeReimbursementDetailsAdmin> selectedReimList = RecordUtilityClass.getListofEmployeeReimbursementDetailsAdmin(empReimbursementList);
            List<Employee_Mileage__c> driverMileagesList =  RecordUtilityClass.getMileagesList();
            driverMileagesList[0].Trip_Id__c = 104976448;
            update driverMileagesList;
            system.debug('selected List'+selectedReimList);
            approvedIdList.add(driverMileagesList[0].id);
            
            
            System.debug('approvedIdList'+approvedIdList);
            Test.startTest();
            
            Database.executeBatch(new ChangeTripStatusinTripLog(approvedIdList ,rejectedIdList,'test','test@gmail.com') );
            //ChangeTripStatusinTripLog.getMileages();
            Test.stopTest();



    }
    public static testmethod void method2() {

        SendEmailToMe__c sendemailme = new SendEmailToMe__c();
        sendemailme.name = 'ChangeTripStatusinTripLog';
        sendemailme.Send_email_to_me__c = true;
        insert sendemailme;
        
        SendEmailonDeactivation__c sendemailme1 = new SendEmailonDeactivation__c();
        sendemailme1.name = 'mileageprocess';
        sendemailme1.Send_to_me__c = true;
        sendemailme1.BCCEmailaddresses__c = 'abc@gmail.com';
        sendemailme1.Send_to_Admin__c = true;
        sendemailme1.Send_to_Manager__c = true;
        insert sendemailme1;

        RecordUtilityClass.createRecordsAdminDashboardController();
            Test.setMock(HttpCalloutMock.class, new ChangeTripStatusinTripLogTestMock());
            Account currentAccount = RecordUtilityClass.getAccount(); // retriving the Accounts EmployeeMileagesForCalculation
            Contact currentAdmin = RecordUtilityClass.getAdminContact(); // Retriving the Admin with limit 1
            Contact selectedDriver = RecordUtilityClass.getDriverContact();
            List<String> approvedIdList = new List<String>();
        
            List<String> rejectedIdList = new List<String>();   
            List<Employee_Reimbursement__c> empReimbursementList = RecordUtilityClass.getEmployee_Reimbursement(currentAccount.id);
            List<EmployeeReimbursementDetailsAdmin> selectedReimList = RecordUtilityClass.getListofEmployeeReimbursementDetailsAdmin(empReimbursementList);
            List<Employee_Mileage__c> driverMileagesList =  RecordUtilityClass.getMileagesList();
            driverMileagesList[0].Trip_Id__c = 104976448;
        	driverMileagesList[0].Trip_Date__c = system.today().toStartOfMonth().addDays(-1);
        	driverMileagesList[1].Trip_Id__c = 104976442;
            update driverMileagesList;
        	approvedIdList.add(driverMileagesList[0].id);
        	approvedIdList.add(driverMileagesList[1].id);
            system.debug('selected List'+selectedReimList);
            rejectedIdList.add(driverMileagesList[0].id);
            
        	ChangeTripStatusinTripLog obj = new ChangeTripStatusinTripLog(approvedIdList ,rejectedIdList,'test','test@gmail.com');
            obj.UpdateMileages(approvedIdList,'Approved');
        ChangeTripStatusinTripLog.BuildBody('Approved',approvedIdList);
        obj.callPutApi('asdfghjytrew56789jhgfd', '', selectedDriver.id, empReimbursementList[0].id, 10);
            System.debug('approvedIdList'+approvedIdList);
            Test.startTest();
            
            Database.executeBatch(new ChangeTripStatusinTripLog(approvedIdList ,rejectedIdList,'test','test@gmail.com') );
            //ChangeTripStatusinTripLog.getMileages();
            Test.stopTest();



    }
}